name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-docker@v2
      with:
        dockerfile: Dockerfile
        container-name: build-container

    - name: Build inside Docker
      run: |
        docker build -t my-c-project .
        docker run --name my-c-project-container my-c-project make

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-binary-artifact
        path: sample
